import { type ReactNode } from 'react';
import '../styles/globals.css';
import { DarkModeProvider } from '@/context/DarkModeContext';
import StyledComponentsRegistry from '@/lib/registry';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <main className='min-h-screen bg-background flex flex-col items-center'>
          <StyledComponentsRegistry>
            <DarkModeProvider>{children}</DarkModeProvider>
          </StyledComponentsRegistry>
        </main>
      </body>
    </html>
  );
}
