import { type ReactNode } from 'react';
import '../styles/globals.css';
import { DarkModeProvider } from '@/context/DarkModeContext';
import Header from '@/components/Header';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import StyledComponentsRegistry from '@/lib/registry';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang='en' className='h-full'>
      <body className='h-full'>
        <StyledComponentsRegistry>
          <DarkModeProvider>
            <Header user={user} />
            <main className='mx-auto max-w-7xl py-6 sm:px-6 lg:px-8 bg-gray-200 dark:bg-gray-900'>{children}</main>
          </DarkModeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
