import { type ReactNode } from 'react';
import '../styles/globals.css';
import { DarkModeProvider } from '@/context/DarkModeContext';
import StyledComponentsRegistry from '@/lib/registry';
import Header from '@/components/Header';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang='en'>
      <body>
        <main className='min-h-screen bg-background flex flex-col items-center bg-white dark:bg-slate-800'>
          <StyledComponentsRegistry>
            <DarkModeProvider>
              <Header user={user} />
              <div className='w-full flex flex-col items-center'>{children}</div>
            </DarkModeProvider>
          </StyledComponentsRegistry>
        </main>
      </body>
    </html>
  );
}
